### ISSUE TITLE
Issue loading the Galaxy10 dataset 

### ISSUE THREAD

**Issue by fshmcallister** [henrysky/astroNN#15]
Thank you for this lovely library first and foremost.

I am trying to access the Galaxy10 DECals dataset (as opposed to the SDSS one) without using the h5 reader as I want to use it as a colab demo.

I've run both `! pip install astroNN` and tried cloning directly into the colab following your instructions on this commit: https://github.com/henrysky/astroNN/commit/9dcd394fb883e966b86096d22dc0cf9a3faa9892

Despite that, using `load_galaxy10` still seems to be loading the SDSS dataset and not the DECals. Do you have any guidance?

I've looked at your code and I can't see why it's loading the old dataset. 

Maybe the issue is in imports?

```
# Import statements
 
from astroNN.datasets import load_galaxy10
from tensorflow.keras import utils
 
# To load images and labels (will download automatically at the first time)
# labels corresponds to galaxy classes as specified by Galaxy Zoo
images, labels = load_galaxy10()
```

Thank you so much for your help!

**Comment by henrysky** [comment]
Can you try to delete the folder `~/.astroNN`.

astroNN version on pip is old and does not support Galaxy10 DECals. So you are right to use the latest commit.

**Comment by fshmcallister** [comment]
Hi Henry! Thanks for the response.

Yep, cleared it, and redid the git clone in the CoLab and got this error:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-f237cb2ade41> in <module>()
      1 # Import statements
      2 
----> 3 from astroNN.datasets import load_galaxy10
      4 from tensorflow.keras import utils
      5 

ModuleNotFoundError: No module named 'astroNN.datasets'

---------------------------------------------------------------
```

I'm not sure why this is the case, since doing some jumping around I can find the datasets folder manually. 
I must admit though I'm not familiar with creating python packages, so I'm a bit lost as to why.

I have also tried running `setup.py install` and still get the same error.

Thank you again for your help!

**Comment by henrysky** [comment]
Did you run your ipython or script inside astroNN folder? You cannot run script or ipython inside astroNN folder.

Can you even just do `import astroNN`, if error raised then you should `pip uninstall astroNN` and `python setup.py develop` again

**Comment by fshmcallister** [comment]
Hi Henry!

We did those, and it still didn't work. To get it to work in CoLab (at least for us) we did the following in a cell:

```
!pip install tensorflow==2.5.0 -q
!pip install tensorflow_probability -q
!pip install git+https://github.com/henrysky/astroNN.git 
```

**Comment by henrysky** [comment]
Thanks! I have updated the docs to reflect this 374e7c2
